import { setAllDuas } from "../lib/db.js";
import { nanoid } from "nanoid";

const DUA_DATA = [
  // ── MORNING ──────────────────────────────────────────────────────────────
  { title: "Waking Up", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur", meaningEnglish: "All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.", source: "Bukhari", category: "Morning", isPopular: true },
  { title: "Morning Supplication", arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ", transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan-nushur", meaningEnglish: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is our resurrection.", source: "Tirmidhi", category: "Morning", isPopular: true },
  { title: "Dua for Good Day", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا", transliteration: "Allahumma inni as'aluka 'ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbalan", meaningEnglish: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.", source: "Ibn Majah", category: "Morning", isPopular: true },
  { title: "Morning Barakah Dua", arabic: "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ", transliteration: "Allahumma ma asbaha bi min ni'matin fa minka wahdaka la sharika laka falakal-hamdu wa lakash-shukr", meaningEnglish: "O Allah, whatever blessing I have this morning is from You alone. To You belongs all praise and thanks.", source: "Abu Dawud", category: "Morning", isPopular: true },
  { title: "Tasbih of the Morning", arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ", transliteration: "Subhanallahi wa bihamdihi 'adada khalqihi wa rida nafsihi wa zinata 'arshihi wa midada kalimatihi", meaningEnglish: "Glory and praise be to Allah as many times as His creation, as much as pleases Him, as heavy as His Throne, and as much as the ink of His words.", source: "Muslim", category: "Morning", isPopular: false },
  { title: "Protection at Dawn", arabic: "اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ", transliteration: "Allahumma inni asbahtu ushiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqika annaka Allahu la ilaha illa ant", meaningEnglish: "O Allah, I have entered the morning calling You, the bearers of Your Throne, Your angels, and all of Your creation to witness that You are Allah, none has the right to be worshipped except You.", source: "Abu Dawud", category: "Morning", isPopular: false },

  // ── EVENING ──────────────────────────────────────────────────────────────
  { title: "Evening Supplication", arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ", transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal-masir", meaningEnglish: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the final return.", source: "Tirmidhi", category: "Evening", isPopular: true },
  { title: "Ayatul Kursi (Evening)", arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum", meaningEnglish: "Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. (Recite full Ayatul Kursi)", source: "Quran 2:255", category: "Evening", isPopular: true },
  { title: "Evening Barakah Dua", arabic: "اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ", transliteration: "Allahumma ma amsa bi min ni'matin aw bi-ahadin min khalqika fa minka wahdaka la sharika lak", meaningEnglish: "O Allah, whatever blessing I have in the evening, or any of Your creation, is from You alone, with no partner.", source: "Abu Dawud", category: "Evening", isPopular: false },
  { title: "Seeking Refuge at Dusk", arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimati-llahit-tammati min sharri ma khalaq", meaningEnglish: "I seek refuge in the perfect words of Allah from the evil of what He has created.", source: "Muslim", category: "Evening", isPopular: true },
  { title: "Evening Remembrance", arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ", transliteration: "Amsayna wa amsal-mulku lillahi wal-hamdu lillahi la ilaha illallahu wahdahu la sharika lah", meaningEnglish: "We have entered the evening and at this very time all sovereignty belongs to Allah, and all praise is for Allah. There is no god but Allah alone with no partner.", source: "Muslim", category: "Evening", isPopular: true },
  { title: "Three Quls (Evening)", arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ", transliteration: "Qul Huwa Allahu Ahad (recite Surahs Ikhlas, Falaq, Nas 3x)", meaningEnglish: "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas three times each for protection through the evening.", source: "Abu Dawud", category: "Evening", isPopular: true },

  // ── PROTECTION ────────────────────────────────────────────────────────────
  { title: "Protection from Evil", arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimati-llahit-tammati min sharri ma khalaq", meaningEnglish: "I seek refuge in the perfect words of Allah from the evil of what He has created.", source: "Muslim", category: "Protection", isPopular: true },
  { title: "Dua for Protection from Hardship", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani wal-'ajzi wal-kasali", meaningEnglish: "O Allah, I seek refuge in You from anxiety, sorrow, weakness, and laziness.", source: "Bukhari", category: "Protection", isPopular: true },
  { title: "The Three Quls for Protection", arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ", transliteration: "Qul Huwa Allahu Ahad", meaningEnglish: "Say: He is Allah, the One. (Recite Surahs Ikhlas, Falaq, Nas 3x)", source: "Quran 112-114", category: "Protection", isPopular: true },
  { title: "Protection When Leaving Home", arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "Bismillahi tawakkaltu 'alallahi wa la hawla wa la quwwata illa billah", meaningEnglish: "In the name of Allah, I put my trust in Allah, and there is no power or might except with Allah.", source: "Tirmidhi", category: "Protection", isPopular: true },
  { title: "Shield from Shaytan", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الشَّيْطَانِ الرَّجِيمِ", transliteration: "Allahumma inni a'udhu bika minash-shaytanir-rajim", meaningEnglish: "O Allah, I seek refuge with You from the accursed devil.", source: "Abu Dawud", category: "Protection", isPopular: false },
  { title: "Protection of Family", arabic: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", transliteration: "U'idhukuma bikalimati-llahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah", meaningEnglish: "I seek protection for you in the perfect words of Allah from every devil, every poisonous creature, and every evil eye.", source: "Bukhari", category: "Protection", isPopular: false },

  // ── FORGIVENESS ───────────────────────────────────────────────────────────
  { title: "Sayyid al-Istighfar", arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ", transliteration: "Allahumma anta rabbi la ilaha illa anta khalaqtani wa ana 'abduka wa ana 'ala 'ahdika wa wa'dika mastata't", meaningEnglish: "O Allah, You are my Lord, there is none worthy of worship but You. You created me and I am your servant, and I am faithful to my covenant and promise to You as much as I can.", source: "Bukhari", category: "Forgiveness", isPopular: true },
  { title: "Seeking Forgiveness", arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ", transliteration: "Astaghfiru-llahul-'adhimal-ladhi la ilaha illa huwal-hayyul-qayyumu wa atubu ilayh", meaningEnglish: "I seek forgiveness from Allah, the Magnificent, beside whom there is no god, the Ever-Living, the Eternal, and I repent to Him.", source: "Tirmidhi", category: "Forgiveness", isPopular: true },
  { title: "Repentance", arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", transliteration: "Rabbighfir li wa tub 'alayya innaka anta-ttawwabur-rahim", meaningEnglish: "My Lord, forgive me and accept my repentance. You are the Accepter of repentance, the Merciful.", source: "Abu Dawud", category: "Forgiveness", isPopular: true },
  { title: "Dua of Adam AS", arabic: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ", transliteration: "Rabbana dhalamna anfusana wa illam taghfir lana wa tarhamna lanakunanna minal-khásirin", meaningEnglish: "Our Lord, we have wronged ourselves. If You do not forgive us and have mercy upon us, we will surely be among the losers.", source: "Quran 7:23", category: "Forgiveness", isPopular: true },
  { title: "The Complete Tawbah", arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ دِقَّهُ وَجِلَّهُ وَأَوَّلَهُ وَآخِرَهُ وَعَلَانِيَتَهُ وَسِرَّهُ", transliteration: "Allahummaghfir li dhanbi kullahu diqqahu wa jillahu wa awwalahu wa akhirahu wa 'alaniyyatahu wa sirrahu", meaningEnglish: "O Allah, forgive me all my sins, the small and the great, the first and the last, the open and the secret.", source: "Muslim", category: "Forgiveness", isPopular: false },
  { title: "Forgiveness and Mercy", arabic: "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ", transliteration: "Rabbanaghfir lana wa li-ikhwaninal-ladhina sabaquna bil-iman", meaningEnglish: "Our Lord, forgive us and our brothers who preceded us in faith.", source: "Quran 59:10", category: "Forgiveness", isPopular: false },

  // ── SALAH ────────────────────────────────────────────────────────────────
  { title: "Before Salah (Wudu Completion)", arabic: "اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", transliteration: "Allahumma-j'alni minat-tawwabin wa-j'alni minal-mutatahhirin", meaningEnglish: "O Allah, make me among those who repent and among those who purify themselves.", source: "Tirmidhi", category: "Salah", isPopular: false },
  { title: "After Salah", arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Allahumma anta-s-salamu wa minka-s-salamu tabarakta ya dhal-jalali wal-ikram", meaningEnglish: "O Allah, You are Peace and from You is peace. Blessed are You, O Possessor of Majesty and Honor.", source: "Muslim", category: "Salah", isPopular: true },
  { title: "Dua for Khushoo in Salah", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ وَمِنْ قَلْبٍ لَا يَخْشَعُ", transliteration: "Allahumma inni a'udhu bika min 'ilmin la yanfa'u wa min qalbin la yakhsha'", meaningEnglish: "O Allah, I seek refuge in You from knowledge that does not benefit and from a heart that does not fear You.", source: "Muslim", category: "Salah", isPopular: true },
  { title: "Entering the Masjid", arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", transliteration: "Allahumma-ftah li abwaba rahmatik", meaningEnglish: "O Allah, open the gates of Your mercy for me.", source: "Muslim", category: "Salah", isPopular: true },
  { title: "Exiting the Masjid", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", transliteration: "Allahumma inni as'aluka min fadlik", meaningEnglish: "O Allah, I ask You of Your bounty.", source: "Muslim", category: "Salah", isPopular: false },
  { title: "Post-Fajr Dua", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا", transliteration: "Allahumma inni as'aluka 'ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbalan", meaningEnglish: "O Allah, I ask You for beneficial knowledge, pure provision, and accepted deeds.", source: "Ibn Majah", category: "Salah", isPopular: false },

  // ── DAILY LIFE ────────────────────────────────────────────────────────────
  { title: "Before Eating", arabic: "بِسْمِ اللَّهِ", transliteration: "Bismillah", meaningEnglish: "In the name of Allah.", source: "Abu Dawud", category: "Daily Life", isPopular: true },
  { title: "After Eating", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimin", meaningEnglish: "Praise be to Allah who fed us and gave us drink and made us Muslims.", source: "Abu Dawud", category: "Daily Life", isPopular: true },
  { title: "Entering the Home", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا", transliteration: "Bismillahi walajna wa bismillahi kharajna wa 'alallahi rabbina tawakkalna", meaningEnglish: "In the name of Allah we enter, and in the name of Allah we leave, and upon Allah our Lord we put our trust.", source: "Abu Dawud", category: "Daily Life", isPopular: true },
  { title: "Entering the Bathroom", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ", transliteration: "Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith", meaningEnglish: "O Allah, I seek refuge with You from male and female devils.", source: "Bukhari", category: "Daily Life", isPopular: false },
  { title: "When Wearing New Clothes", arabic: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ", transliteration: "Alhamdu lillahil-ladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah", meaningEnglish: "Praise be to Allah who clothed me with this and provided it for me with no power or strength from myself.", source: "Abu Dawud", category: "Daily Life", isPopular: false },
  { title: "When Looking in the Mirror", arabic: "اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي", transliteration: "Allahumma kama hassanta khalqi fahassin khuluqi", meaningEnglish: "O Allah, just as You have made my external features good, make my character good as well.", source: "Ahmad", category: "Daily Life", isPopular: true },
  { title: "Before Starting Any Work", arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ", transliteration: "Bismillahir-rahmanir-rahim", meaningEnglish: "In the name of Allah, the Most Gracious, the Most Merciful.", source: "Quran 1:1", category: "Daily Life", isPopular: true },

  // ── SLEEP ─────────────────────────────────────────────────────────────────
  { title: "Before Sleeping", arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismika Allahumma amutu wa ahya", meaningEnglish: "In Your name, O Allah, I die and I live.", source: "Bukhari", category: "Sleep", isPopular: true },
  { title: "Dua for Good Sleep", arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak", meaningEnglish: "O Allah, save me from Your punishment on the Day You resurrect Your servants.", source: "Abu Dawud", category: "Sleep", isPopular: false },
  { title: "Sleeping on the Right Side", arabic: "اللَّهُمَّ بِاسْمِكَ أَحْيَا وَأَمُوتُ", transliteration: "Allahumma bismika ahya wa amut", meaningEnglish: "O Allah, with Your name I live and die.", source: "Bukhari", category: "Sleep", isPopular: false },
  { title: "Ayatul Kursi Before Bed", arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ", transliteration: "Allahu la ilaha illa huwal-hayyul-qayyumu la ta'khudhuhu sinatun wa la nawm", meaningEnglish: "Allah, there is no deity except Him, the Ever-Living, the Sustainer. Neither drowsiness overtakes Him nor sleep.", source: "Quran 2:255", category: "Sleep", isPopular: true },
  { title: "Dua for Restful Sleep", arabic: "بِسْمِكَ رَبِّي وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ", transliteration: "Bismika rabbi wada'tu janbi wa bika arfa'uh", meaningEnglish: "In Your name, my Lord, I lie down and in Your name I rise.", source: "Bukhari", category: "Sleep", isPopular: true },
  { title: "Surah Al-Mulk Before Sleep", arabic: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", transliteration: "Tabarakal-ladhi biyadihil-mulku wa huwa 'ala kulli shay'in qadir", meaningEnglish: "Blessed is He in whose hand is dominion, and He is over all things competent. (Read Surah Al-Mulk for protection from punishment of grave.)", source: "Quran 67:1", category: "Sleep", isPopular: true },

  // ── TRAVEL ────────────────────────────────────────────────────────────────
  { title: "Before Travel", arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ", transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila rabbina lamunqalibun", meaningEnglish: "Glory be to Him who has subjected this to us, and we could not have [otherwise] subdued it. And indeed we, to our Lord, will return.", source: "Quran 43:13-14", category: "Travel", isPopular: true },
  { title: "Dua for a Safe Journey", arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى", transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa", meaningEnglish: "O Allah, we ask You on this journey of ours for righteousness and piety.", source: "Muslim", category: "Travel", isPopular: true },
  { title: "Arriving at a Destination", arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimati-llahit-tammati min sharri ma khalaq", meaningEnglish: "I seek refuge in the perfect words of Allah from the evil of what He created. (Say upon arrival at any place.)", source: "Muslim", category: "Travel", isPopular: false },
  { title: "Dua on Returning Home", arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ", transliteration: "Ayibuna ta'ibuna 'abiduna lirabbina hamidun", meaningEnglish: "We return, repenting, worshipping, and praising our Lord.", source: "Bukhari", category: "Travel", isPopular: true },
  { title: "Dua Before Boarding", arabic: "بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا إِنَّ رَبِّي لَغَفُورٌ رَّحِيمٌ", transliteration: "Bismillahi majriha wa mursaha inna rabbi laghafurur-rahim", meaningEnglish: "In the name of Allah is its course and its anchorage. Indeed, my Lord is Forgiving and Merciful.", source: "Quran 11:41", category: "Travel", isPopular: false },

  // ── HARDSHIP ─────────────────────────────────────────────────────────────
  { title: "Dua of Yunus AS", arabic: "لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa anta subhanaka inni kuntu minadh-dhalimin", meaningEnglish: "None has the right to be worshipped but You, Glorified are You. Truly, I have been of the wrongdoers.", source: "Quran 21:87", category: "Hardship", isPopular: true },
  { title: "Dua for Strength", arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي", transliteration: "Rabbish-rah li sadri wa yassir li amri wahlul 'uqdatan min lisani", meaningEnglish: "My Lord, expand for me my breast, ease for me my task, and untie the knot from my tongue.", source: "Quran 20:25-27", category: "Hardship", isPopular: true },
  { title: "Hasbunallah", arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", transliteration: "Hasbunallahu wa ni'mal-wakil", meaningEnglish: "Allah is sufficient for us, and He is the best Disposer of affairs.", source: "Quran 3:173", category: "Hardship", isPopular: true },
  { title: "Dua of Ayyub AS (Illness)", arabic: "أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ", transliteration: "Anni massaniyad-durru wa anta arhamur-rahimin", meaningEnglish: "Indeed, adversity has touched me, and You are the Most Merciful of the merciful.", source: "Quran 21:83", category: "Hardship", isPopular: true },
  { title: "Dua of Ibrahim AS in Fire", arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ", transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu", meaningEnglish: "Sufficient for me is Allah; there is no deity except Him. On Him I have relied.", source: "Quran 9:129", category: "Hardship", isPopular: false },
  { title: "When Struck by Calamity", arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي", transliteration: "Inna lillahi wa inna ilayhi raji'un, Allahumma'jurni fi musibati", meaningEnglish: "Indeed we belong to Allah, and indeed to Him we will return. O Allah, reward me in my affliction.", source: "Muslim", category: "Hardship", isPopular: true },

  // ── GRATITUDE ────────────────────────────────────────────────────────────
  { title: "Dua of Gratitude", arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ", transliteration: "Rabbi awzi'ni an ashkura ni'mataka-llati an'amta 'alayya wa 'ala walidayya", meaningEnglish: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents.", source: "Quran 27:19", category: "Gratitude", isPopular: true },
  { title: "Alhamdulillah Expression", arabic: "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ", transliteration: "Alhamdu lillahil-ladhi bini'matihi tatimmus-salihat", meaningEnglish: "Praise be to Allah by whose grace all good things are accomplished.", source: "Ibn Majah", category: "Gratitude", isPopular: true },
  { title: "Dua for Shukr", arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ", transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik", meaningEnglish: "O Allah, help me to remember You, to give thanks to You, and to worship You in an excellent manner.", source: "Abu Dawud", category: "Gratitude", isPopular: true },
  { title: "Thankfulness for Blessings", arabic: "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ", transliteration: "Alhamdu lillahi 'ala kulli hal", meaningEnglish: "Praise be to Allah in every circumstance.", source: "Ibn Majah", category: "Gratitude", isPopular: false },
  { title: "Gratitude After Eating", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ", transliteration: "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah", meaningEnglish: "Praise be to Allah who fed me this and provided it for me without any power or strength from me.", source: "Tirmidhi", category: "Gratitude", isPopular: false },

  // ── FAMILY ────────────────────────────────────────────────────────────────
  { title: "Dua for Parents", arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", transliteration: "Rabbir-hamhuma kama rabbayani saghira", meaningEnglish: "My Lord, have mercy upon them as they brought me up when I was small.", source: "Quran 17:24", category: "Family", isPopular: true },
  { title: "Dua for Righteous Spouse", arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama", meaningEnglish: "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.", source: "Quran 25:74", category: "Family", isPopular: true },
  { title: "Dua for Righteous Children", arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ", transliteration: "Rabbi hab li minas-salihin", meaningEnglish: "My Lord, grant me [a child] from among the righteous.", source: "Quran 37:100", category: "Family", isPopular: true },
  { title: "Dua for Family Unity", arabic: "رَبَّنَا اغْفِرْ لَنَا وَلِوَالِدِينَا وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ", transliteration: "Rabbanaghfir lana wa liwalidina wa lil-mu'minina yawma yaqumul-hisab", meaningEnglish: "Our Lord, forgive me and my parents and the believers the Day the account is established.", source: "Quran 14:41", category: "Family", isPopular: false },
  { title: "Dua for a Blessed Home", arabic: "رَبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا", transliteration: "Rabbi adkhilni mudkhala sidqin wa akhrjni mukhraja sidqin waj'al li min ladunka sultanan nasira", meaningEnglish: "My Lord, cause me to enter a truthful entrance and to exit a truthful exit and grant me from Yourself a supporting authority.", source: "Quran 17:80", category: "Family", isPopular: false },

  // ── QURAN ─────────────────────────────────────────────────────────────────
  { title: "Before Reciting Quran", arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", transliteration: "A'udhu billahi minash-shaytanir-rajim", meaningEnglish: "I seek refuge with Allah from the accursed devil.", source: "Quran 16:98", category: "Quran", isPopular: true },
  { title: "Dua for Understanding Quran", arabic: "رَبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni 'ilma", meaningEnglish: "My Lord, increase me in knowledge.", source: "Quran 20:114", category: "Quran", isPopular: true },
  { title: "Dua for Quran Memorization", arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنفَعُنِي", transliteration: "Allahumma-nfa'ni bima 'allamtani wa 'allimni ma yanfa'uni", meaningEnglish: "O Allah, benefit me with what You have taught me, and teach me that which will benefit me.", source: "Tirmidhi", category: "Quran", isPopular: true },
  { title: "After Reciting Quran", arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ لَا إِلَهَ إِلَّا أَنتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ", transliteration: "Subhanakal-lahumma wa bihamdika la ilaha illa anta astaghfiruka wa atubu ilayk", meaningEnglish: "Glory and praise be to You, O Allah. There is none worthy of worship but You. I seek Your forgiveness and repent to You.", source: "Tirmidhi", category: "Quran", isPopular: false },
  { title: "Dua for Open Heart to Quran", arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً", transliteration: "Rabbana la tuzigh qulubana ba'da idh hadaytana wa hab lana min ladunka rahmah", meaningEnglish: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy.", source: "Quran 3:8", category: "Quran", isPopular: false },

  // ── FOOD ──────────────────────────────────────────────────────────────────
  { title: "Bismillah Before Eating", arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ", transliteration: "Bismillahi wa 'ala barakatillah", meaningEnglish: "In the name of Allah and with the blessings of Allah.", source: "Ibn Majah", category: "Food", isPopular: true },
  { title: "After Eating", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimin", meaningEnglish: "Praise be to Allah who fed us and gave us drink and made us Muslims.", source: "Abu Dawud", category: "Food", isPopular: true },
  { title: "If Forgot to Say Bismillah", arabic: "بِسْمِ اللَّهِ فِي أَوَّلِهِ وَآخِرِهِ", transliteration: "Bismillahi fi awwalihi wa akhirih", meaningEnglish: "In the name of Allah at its beginning and its end.", source: "Abu Dawud", category: "Food", isPopular: true },
  { title: "Dua for Host After Eating", arabic: "اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ", transliteration: "Allahumma barik lahum fima razaqtahum waghfir lahum warhamhum", meaningEnglish: "O Allah, bless them in what You have provided for them, and forgive them and have mercy on them.", source: "Muslim", category: "Food", isPopular: false },
  { title: "Gratitude for Food", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ", transliteration: "Alhamdu lillahil-ladhi at'amani hadha min ghayri hawlin minni wa la quwwah", meaningEnglish: "Praise be to Allah who fed me this without any power or strength from me.", source: "Tirmidhi", category: "Food", isPopular: false },

  // ── ANXIETY ───────────────────────────────────────────────────────────────
  { title: "Hearts at Rest", arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", transliteration: "Ala bidhikrillahi tatma'innul-qulub", meaningEnglish: "Verily, in the remembrance of Allah do hearts find rest.", source: "Quran 13:28", category: "Anxiety", isPopular: true },
  { title: "Dua Against Worry", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحُزْنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-huzni wal-'ajzi wal-kasali wal-bukhli wal-jubn", meaningEnglish: "O Allah, I seek refuge in You from anxiety, sorrow, weakness, laziness, miserliness, and cowardice.", source: "Bukhari", category: "Anxiety", isPopular: true },
  { title: "Dua of Yunus for Distress", arabic: "لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa anta subhanaka inni kuntu minadh-dhalimin", meaningEnglish: "There is no god but You, glory be to You. Indeed I was of the wrongdoers.", source: "Quran 21:87", category: "Anxiety", isPopular: true },
  { title: "When Overwhelmed", arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'adhim", meaningEnglish: "Allah is sufficient for me; there is no deity except Him. On Him I have relied, and He is Lord of the Great Throne.", source: "Quran 9:129", category: "Anxiety", isPopular: true },
  { title: "Trust in Allah's Plan", arabic: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", transliteration: "Wa man yatawakkal 'alallahi fahuwa hasbuh", meaningEnglish: "And whoever relies upon Allah, then He is sufficient for him.", source: "Quran 65:3", category: "Anxiety", isPopular: false },
  { title: "Dua for Relief", arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا", transliteration: "Allahumma la sahla illa ma ja'altahu sahlan wa anta taj'alul-hazna idha shi'ta sahla", meaningEnglish: "O Allah, there is no ease except what You make easy, and You make the difficult easy when You will.", source: "Ibn Hibban", category: "Anxiety", isPopular: true },

  // ── GRIEF ─────────────────────────────────────────────────────────────────
  { title: "Inna Lillahi (At Loss)", arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", transliteration: "Inna lillahi wa inna ilayhi raji'un", meaningEnglish: "Indeed, we belong to Allah and indeed to Him we will return.", source: "Quran 2:156", category: "Grief", isPopular: true },
  { title: "Dua for the Bereaved", arabic: "اللَّهُمَّ اغْفِرْ لِفُلَانٍ وَارْفَعْ دَرَجَتَهُ فِي الْمَهْدِيِّينَ", transliteration: "Allahummaghfir li-fulanin warfa' darajatahu fil-mahdiyyin", meaningEnglish: "O Allah, forgive [him/her] and elevate his/her station among the guided.", source: "Muslim", category: "Grief", isPopular: true },
  { title: "Allah with the Patient", arabic: "وَبَشِّرِ الصَّابِرِينَ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ", transliteration: "Wa bashshiris-sabirin, alladhina idha asabathum musibatun qalu inna lillahi wa inna ilayhi raji'un", meaningEnglish: "And give good tidings to the patient, those who, when disaster strikes them, say: Indeed, we belong to Allah and to Him we shall return.", source: "Quran 2:155-156", category: "Grief", isPopular: true },
  { title: "Dua for a Lost Loved One", arabic: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ", transliteration: "Allahummaghfir lahu warhamhu wa 'afihi wa'fu 'anhu", meaningEnglish: "O Allah, forgive him/her, have mercy on him/her, protect him/her, and pardon him/her.", source: "Muslim", category: "Grief", isPopular: true },
  { title: "Comfort in Allah", arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", transliteration: "Inna ma'al-'usri yusra", meaningEnglish: "Indeed, with hardship comes ease.", source: "Quran 94:6", category: "Grief", isPopular: false },
  { title: "Dua for the Grieving Heart", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْحُزْنِ وَالْكَسَلِ", transliteration: "Allahumma inni a'udhu bika minal-huzni wal-kasal", meaningEnglish: "O Allah, I seek refuge in You from grief and laziness.", source: "Bukhari", category: "Grief", isPopular: false },

  // ── WORK ──────────────────────────────────────────────────────────────────
  { title: "Dua for Success in Work", arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar", meaningEnglish: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.", source: "Quran 2:201", category: "Work", isPopular: true },
  { title: "Barakah in Earnings", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ رِزْقًا طَيِّبًا وَعِلْمًا نَافِعًا وَعَمَلًا مُتَقَبَّلًا", transliteration: "Allahumma inni as'aluka rizqan tayyiban wa 'ilman nafi'an wa 'amalan mutaqabbalan", meaningEnglish: "O Allah, I ask You for pure provision, beneficial knowledge, and accepted deeds.", source: "Ibn Majah", category: "Work", isPopular: true },
  { title: "Tawakkul at Work", arabic: "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ", transliteration: "Wa man yattaqillaha yaj'al lahu makhrajan wa yarzuqhu min haythu la yahtasib", meaningEnglish: "Whoever fears Allah, He will make for him a way out and provide for him from where he does not expect.", source: "Quran 65:2-3", category: "Work", isPopular: true },
  { title: "Dua for Halal Rizq", arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ", transliteration: "Allahumma-kfini bihalálika 'an haramika wa aghnimi bifadlika 'amman siwak", meaningEnglish: "O Allah, suffice me with what You have made lawful against what You have made unlawful, and make me independent of all others by Your bounty.", source: "Tirmidhi", category: "Work", isPopular: true },
  { title: "Before Starting a Task", arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا", transliteration: "Allahumma la sahla illa ma ja'altahu sahla", meaningEnglish: "O Allah, nothing is easy except what You make easy.", source: "Ibn Hibban", category: "Work", isPopular: false },
  { title: "Dua for Barakah in Time", arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا", transliteration: "Allahumma barik lana fima razaqtana", meaningEnglish: "O Allah, bless us in what You have provided for us.", source: "Ibn Majah", category: "Work", isPopular: false },

  // ── STUDY ─────────────────────────────────────────────────────────────────
  { title: "Increase in Knowledge", arabic: "رَّبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni 'ilma", meaningEnglish: "My Lord, increase me in knowledge.", source: "Quran 20:114", category: "Study", isPopular: true },
  { title: "Dua Before Studying", arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنفَعُنِي وَزِدْنِي عِلْمًا", transliteration: "Allahumma-nfa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma", meaningEnglish: "O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.", source: "Tirmidhi", category: "Study", isPopular: true },
  { title: "Dua for Good Memory", arabic: "سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا إِنَّكَ أَنتَ الْعَلِيمُ الْحَكِيمُ", transliteration: "Subhanaka la 'ilma lana illa ma 'allamtana innaka antal-'alimul-hakim", meaningEnglish: "Glory be to You, we have no knowledge except what You have taught us. Indeed, it is You who is the Knowing, the Wise.", source: "Quran 2:32", category: "Study", isPopular: true },
  { title: "Dua for Understanding", arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي", transliteration: "Rabbish-rah li sadri wa yassir li amri", meaningEnglish: "My Lord, expand my chest and ease my task for me.", source: "Quran 20:25-26", category: "Study", isPopular: true },
  { title: "Dua for Concentration", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنفَعُ", transliteration: "Allahumma inni a'udhu bika min 'ilmin la yanfa'", meaningEnglish: "O Allah, I seek refuge in You from knowledge that does not benefit.", source: "Muslim", category: "Study", isPopular: false },
  { title: "After Completing Study", arabic: "الْحَمْدُ لِلَّهِ الَّذِي هَدَانَا لِهَذَا وَمَا كُنَّا لِنَهْتَدِيَ لَوْلَا أَنْ هَدَانَا اللَّهُ", transliteration: "Alhamdu lillahil-ladhi hadana lihadha wa ma kunna linahtadiya lawla an hadanallah", meaningEnglish: "Praise be to Allah who guided us to this; we would not have been guided had Allah not guided us.", source: "Quran 7:43", category: "Study", isPopular: false },

  // ── MARRIAGE ──────────────────────────────────────────────────────────────
  { title: "Dua for a Righteous Spouse", arabic: "رَبِّ هَبْ لِي مِن لَّدُنكَ زَوْجًا طَيِّبًا", transliteration: "Rabbi hab li min ladunka zawjan tayyiba", meaningEnglish: "My Lord, grant me from Yourself a good spouse.", source: "Hadith", category: "Marriage", isPopular: true },
  { title: "Dua on Wedding Night", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا جَبَلْتَهَا عَلَيْهِ", transliteration: "Allahumma inni as'aluka khayrahá wa khayra ma jabaltaha 'alayh", meaningEnglish: "O Allah, I ask You of her goodness and the goodness of what You have made her inclined towards.", source: "Abu Dawud", category: "Marriage", isPopular: true },
  { title: "Blessing on the Couple", arabic: "بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ", transliteration: "Barakallahu laka wa baraka 'alayka wa jama'a baynakuma fi khayr", meaningEnglish: "May Allah bless you and shower His blessings upon you and join you together in goodness.", source: "Abu Dawud", category: "Marriage", isPopular: true },
  { title: "Dua for Marital Harmony", arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yun", meaningEnglish: "Our Lord, grant us comfort in our spouses and children, and make us an example for the righteous.", source: "Quran 25:74", category: "Marriage", isPopular: true },
  { title: "Before Intimacy", arabic: "بِسْمِ اللَّهِ اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا", transliteration: "Bismillah, Allahumma jannibna-sh-shaytana wa jannibish-shaytana ma razaqtana", meaningEnglish: "In the name of Allah. O Allah, keep Satan away from us and keep Satan away from what You bestow upon us.", source: "Bukhari", category: "Marriage", isPopular: false },
  { title: "Dua for a Blessed Marriage", arabic: "اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا", transliteration: "Allahumma allif bayna qulubina wa aslih dhata baynina", meaningEnglish: "O Allah, unite our hearts and set right our mutual affairs.", source: "Abu Dawud", category: "Marriage", isPopular: false },

  // ── CHILDREN ──────────────────────────────────────────────────────────────
  { title: "Dua for Pious Children", arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ", transliteration: "Rabbi hab li minas-salihin", meaningEnglish: "My Lord, grant me [a child] from among the righteous.", source: "Quran 37:100", category: "Children", isPopular: true },
  { title: "Dua of Zakariyya AS", arabic: "رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ", transliteration: "Rabbi la tadharni fardan wa anta khayrul-waritheen", meaningEnglish: "My Lord, do not leave me alone [childless], and You are the best of inheritors.", source: "Quran 21:89", category: "Children", isPopular: true },
  { title: "Dua for Newborn", arabic: "أُعِيذُهُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", transliteration: "U'idhuka bikalimati-llahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah", meaningEnglish: "I seek protection for you in the perfect words of Allah from every devil, every poisonous creature, and every evil eye.", source: "Bukhari", category: "Children", isPopular: true },
  { title: "Dua for Good Character in Children", arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama", meaningEnglish: "Our Lord, grant us in our spouses and offspring the comfort of our eyes and make us a leader for the righteous.", source: "Quran 25:74", category: "Children", isPopular: false },
  { title: "Dua of Ibrahim AS for Children", arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ", transliteration: "Rabbij-'alni muqimash-salati wa min dhurriyyati rabbana wa taqabbal du'a", meaningEnglish: "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication.", source: "Quran 14:40", category: "Children", isPopular: true },
  { title: "Protection for Children", arabic: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ", transliteration: "U'idhukuma bikalimati-llahit-tammati min kulli shaytanin wa hammah", meaningEnglish: "I seek protection for you both in the perfect words of Allah from every devil and harmful creature.", source: "Bukhari", category: "Children", isPopular: false },
];

export async function seedDuas() {
  const duas = DUA_DATA.map((d) => ({
    id: nanoid(),
    madhab: null,
    audioUrl: null,
    tags: [d.category.toLowerCase()],
    isFavorite: false,
    ...d,
  }));

  await setAllDuas(duas);
  console.log(`Seeded ${duas.length} duas`);
}
