import { setNamesOfAllah } from "../lib/db.js";
import { nanoid } from "nanoid";

const NAMES = [
  { number: 1, arabic: "ٱللَّه", transliteration: "Allah", meaningEnglish: "The Greatest Name, the One Who is worshipped", explanation: "The proper name of God, encompassing all His attributes." },
  { number: 2, arabic: "ٱلرَّحْمَـٰن", transliteration: "Ar-Rahman", meaningEnglish: "The Entirely Merciful", explanation: "The One who has vast mercy for all of creation." },
  { number: 3, arabic: "ٱلرَّحِيم", transliteration: "Ar-Raheem", meaningEnglish: "The Especially Merciful", explanation: "The One whose mercy is especially for the believers." },
  { number: 4, arabic: "ٱلْمَلِك", transliteration: "Al-Malik", meaningEnglish: "The Sovereign Lord", explanation: "The absolute owner of all creation." },
  { number: 5, arabic: "ٱلْقُدُّوس", transliteration: "Al-Quddus", meaningEnglish: "The Purest", explanation: "The One who is free from all imperfection." },
  { number: 6, arabic: "ٱلسَّلَام", transliteration: "As-Salam", meaningEnglish: "The Source of Peace", explanation: "The One from whom all peace flows." },
  { number: 7, arabic: "ٱلْمُؤْمِن", transliteration: "Al-Mu'min", meaningEnglish: "The Granter of Security", explanation: "The One who grants peace and security to His creation." },
  { number: 8, arabic: "ٱلْمُهَيْمِن", transliteration: "Al-Muhaymin", meaningEnglish: "The Guardian", explanation: "The One who oversees and protects all." },
  { number: 9, arabic: "ٱلْعَزِيز", transliteration: "Al-'Aziz", meaningEnglish: "The Almighty", explanation: "The Mighty One who is never overcome." },
  { number: 10, arabic: "ٱلْجَبَّار", transliteration: "Al-Jabbar", meaningEnglish: "The Compeller", explanation: "The One who compels and restores all things." },
  { number: 11, arabic: "ٱلْمُتَكَبِّر", transliteration: "Al-Mutakabbir", meaningEnglish: "The Supreme", explanation: "The One who is above all greatness." },
  { number: 12, arabic: "ٱلْخَالِق", transliteration: "Al-Khaliq", meaningEnglish: "The Creator", explanation: "The One who creates from nothing." },
  { number: 13, arabic: "ٱلْبَارِئ", transliteration: "Al-Bari'", meaningEnglish: "The Evolver", explanation: "The One who distinguishes and separates things." },
  { number: 14, arabic: "ٱلْمُصَوِّر", transliteration: "Al-Musawwir", meaningEnglish: "The Fashioner", explanation: "The One who gives form and shape to all things." },
  { number: 15, arabic: "ٱلْغَفَّار", transliteration: "Al-Ghaffar", meaningEnglish: "The Perpetual Forgiver", explanation: "The One who forgives sins repeatedly and completely." },
  { number: 16, arabic: "ٱلْقَهَّار", transliteration: "Al-Qahhar", meaningEnglish: "The Subduer", explanation: "The One who subdues all of creation." },
  { number: 17, arabic: "ٱلْوَهَّاب", transliteration: "Al-Wahhab", meaningEnglish: "The Bestower", explanation: "The One who gives freely and abundantly without expectation." },
  { number: 18, arabic: "ٱلرَّزَّاق", transliteration: "Ar-Razzaq", meaningEnglish: "The Provider", explanation: "The One who provides sustenance for all of creation." },
  { number: 19, arabic: "ٱلْفَتَّاح", transliteration: "Al-Fattah", meaningEnglish: "The Opener", explanation: "The One who opens doors of mercy and provision." },
  { number: 20, arabic: "ٱلْعَلِيم", transliteration: "Al-'Alim", meaningEnglish: "The All-Knowing", explanation: "The One whose knowledge encompasses everything." },
  { number: 21, arabic: "ٱلْقَابِض", transliteration: "Al-Qabid", meaningEnglish: "The Withholder", explanation: "The One who constricts and withholds as He wills." },
  { number: 22, arabic: "ٱلْبَاسِط", transliteration: "Al-Basit", meaningEnglish: "The Extender", explanation: "The One who extends His grace to whom He wills." },
  { number: 23, arabic: "ٱلْخَافِض", transliteration: "Al-Khafid", meaningEnglish: "The Abaser", explanation: "The One who humbles the arrogant." },
  { number: 24, arabic: "ٱلرَّافِع", transliteration: "Ar-Rafi'", meaningEnglish: "The Exalter", explanation: "The One who raises the believers in rank." },
  { number: 25, arabic: "ٱلْمُعِزّ", transliteration: "Al-Mu'izz", meaningEnglish: "The Honorer", explanation: "The One who grants honour and dignity." },
  { number: 26, arabic: "ٱلْمُذِلّ", transliteration: "Al-Mudhil", meaningEnglish: "The Dishonourer", explanation: "The One who humiliates the enemies of truth." },
  { number: 27, arabic: "ٱلسَّمِيع", transliteration: "As-Sami'", meaningEnglish: "The All-Hearing", explanation: "The One who hears all sounds, open and secret." },
  { number: 28, arabic: "ٱلْبَصِير", transliteration: "Al-Basir", meaningEnglish: "The All-Seeing", explanation: "The One who sees everything that is seen and unseen." },
  { number: 29, arabic: "ٱلْحَكَم", transliteration: "Al-Hakam", meaningEnglish: "The Judge", explanation: "The One who judges with complete justice." },
  { number: 30, arabic: "ٱلْعَدْل", transliteration: "Al-'Adl", meaningEnglish: "The Just", explanation: "The One who is perfectly just in all affairs." },
  { number: 31, arabic: "ٱللَّطِيف", transliteration: "Al-Latif", meaningEnglish: "The Subtle One", explanation: "The One who is kind and gentle with His servants." },
  { number: 32, arabic: "ٱلْخَبِير", transliteration: "Al-Khabir", meaningEnglish: "The Acquainted", explanation: "The One who is aware of all things, even the most hidden." },
  { number: 33, arabic: "ٱلْحَلِيم", transliteration: "Al-Halim", meaningEnglish: "The Forbearing", explanation: "The One who is patient and does not rush to punish." },
  { number: 34, arabic: "ٱلْعَظِيم", transliteration: "Al-'Adhim", meaningEnglish: "The Magnificent", explanation: "The One whose greatness is beyond all measure." },
  { number: 35, arabic: "ٱلْغَفُور", transliteration: "Al-Ghafur", meaningEnglish: "The Forgiving", explanation: "The One who forgives sins and covers faults." },
  { number: 36, arabic: "ٱلشَّكُور", transliteration: "Ash-Shakur", meaningEnglish: "The Appreciative", explanation: "The One who rewards abundantly for small deeds." },
  { number: 37, arabic: "ٱلْعَلِيّ", transliteration: "Al-'Ali", meaningEnglish: "The Most High", explanation: "The One who is above all of creation in every way." },
  { number: 38, arabic: "ٱلْكَبِير", transliteration: "Al-Kabir", meaningEnglish: "The Greatest", explanation: "The One who is great beyond all comprehension." },
  { number: 39, arabic: "ٱلْحَفِيظ", transliteration: "Al-Hafidh", meaningEnglish: "The Preserver", explanation: "The One who protects and preserves all things." },
  { number: 40, arabic: "ٱلْمُقِيت", transliteration: "Al-Muqit", meaningEnglish: "The Sustainer", explanation: "The One who provides nourishment for body and soul." },
  { number: 41, arabic: "ٱلْحَسِيب", transliteration: "Al-Hasib", meaningEnglish: "The Reckoner", explanation: "The One who takes account of all deeds." },
  { number: 42, arabic: "ٱلْجَلِيل", transliteration: "Al-Jalil", meaningEnglish: "The Majestic", explanation: "The One of glory and majesty." },
  { number: 43, arabic: "ٱلْكَرِيم", transliteration: "Al-Karim", meaningEnglish: "The Generous", explanation: "The One whose generosity is boundless." },
  { number: 44, arabic: "ٱلرَّقِيب", transliteration: "Ar-Raqib", meaningEnglish: "The Watchful", explanation: "The One who watches over all things at all times." },
  { number: 45, arabic: "ٱلْمُجِيب", transliteration: "Al-Mujib", meaningEnglish: "The Responsive", explanation: "The One who answers every prayer and call." },
  { number: 46, arabic: "ٱلْوَاسِع", transliteration: "Al-Wasi'", meaningEnglish: "The All-Encompassing", explanation: "The One whose mercy and knowledge encompass everything." },
  { number: 47, arabic: "ٱلْحَكِيم", transliteration: "Al-Hakim", meaningEnglish: "The Wise", explanation: "The One whose wisdom is perfect and complete." },
  { number: 48, arabic: "ٱلْوَدُود", transliteration: "Al-Wadud", meaningEnglish: "The Loving", explanation: "The One who loves His righteous servants." },
  { number: 49, arabic: "ٱلْمَجِيد", transliteration: "Al-Majid", meaningEnglish: "The Glorious", explanation: "The One of magnificent glory." },
  { number: 50, arabic: "ٱلْبَاعِث", transliteration: "Al-Ba'ith", meaningEnglish: "The Resurrector", explanation: "The One who will raise all from the dead." },
  { number: 51, arabic: "ٱلشَّهِيد", transliteration: "Ash-Shahid", meaningEnglish: "The Witness", explanation: "The One who is present and witnesses all things." },
  { number: 52, arabic: "ٱلْحَقّ", transliteration: "Al-Haqq", meaningEnglish: "The Truth", explanation: "The One who is the absolute truth and reality." },
  { number: 53, arabic: "ٱلْوَكِيل", transliteration: "Al-Wakil", meaningEnglish: "The Trustee", explanation: "The One upon whom we rely for all matters." },
  { number: 54, arabic: "ٱلْقَوِيّ", transliteration: "Al-Qawiy", meaningEnglish: "The Strong", explanation: "The One of perfect and complete strength." },
  { number: 55, arabic: "ٱلْمَتِين", transliteration: "Al-Matin", meaningEnglish: "The Firm", explanation: "The One of inexhaustible firmness and power." },
  { number: 56, arabic: "ٱلْوَلِيّ", transliteration: "Al-Wali", meaningEnglish: "The Protecting Friend", explanation: "The One who befriends and supports the believers." },
  { number: 57, arabic: "ٱلْحَمِيد", transliteration: "Al-Hamid", meaningEnglish: "The Praiseworthy", explanation: "The One who is deserving of all praise." },
  { number: 58, arabic: "ٱلْمُحْصِي", transliteration: "Al-Muhsi", meaningEnglish: "The Counter", explanation: "The One who has counted and recorded all things." },
  { number: 59, arabic: "ٱلْمُبْدِئ", transliteration: "Al-Mubdi'", meaningEnglish: "The Originator", explanation: "The One who begins and originates creation." },
  { number: 60, arabic: "ٱلْمُعِيد", transliteration: "Al-Mu'id", meaningEnglish: "The Restorer", explanation: "The One who restores creation after death." },
  { number: 61, arabic: "ٱلْمُحْيِي", transliteration: "Al-Muhyi", meaningEnglish: "The Giver of Life", explanation: "The One who gives life to all living things." },
  { number: 62, arabic: "ٱلْمُمِيت", transliteration: "Al-Mumit", meaningEnglish: "The Taker of Life", explanation: "The One who causes death as He wills." },
  { number: 63, arabic: "ٱلْحَيّ", transliteration: "Al-Hayy", meaningEnglish: "The Ever-Living", explanation: "The One who is eternally alive and never dies." },
  { number: 64, arabic: "ٱلْقَيُّوم", transliteration: "Al-Qayyum", meaningEnglish: "The Self-Subsisting", explanation: "The One who sustains all of existence." },
  { number: 65, arabic: "ٱلْوَاجِد", transliteration: "Al-Wajid", meaningEnglish: "The Finder", explanation: "The One who finds and achieves all He wills." },
  { number: 66, arabic: "ٱلْمَاجِد", transliteration: "Al-Majid", meaningEnglish: "The Noble", explanation: "The One of infinite nobility and generosity." },
  { number: 67, arabic: "ٱلْوَاحِد", transliteration: "Al-Wahid", meaningEnglish: "The One", explanation: "The One who has no partner or equal." },
  { number: 68, arabic: "ٱلصَّمَد", transliteration: "As-Samad", meaningEnglish: "The Eternal", explanation: "The One upon whom all creation depends." },
  { number: 69, arabic: "ٱلْقَادِر", transliteration: "Al-Qadir", meaningEnglish: "The Capable", explanation: "The One who has power over all things." },
  { number: 70, arabic: "ٱلْمُقْتَدِر", transliteration: "Al-Muqtadir", meaningEnglish: "The Powerful", explanation: "The One with supreme and irresistible power." },
  { number: 71, arabic: "ٱلْمُقَدِّم", transliteration: "Al-Muqaddim", meaningEnglish: "The Expediter", explanation: "The One who brings forward whom He wills." },
  { number: 72, arabic: "ٱلْمُؤَخِّر", transliteration: "Al-Mu'akhkhir", meaningEnglish: "The Delayer", explanation: "The One who delays whom He wills." },
  { number: 73, arabic: "ٱلْأَوَّل", transliteration: "Al-Awwal", meaningEnglish: "The First", explanation: "The One who existed before all things." },
  { number: 74, arabic: "ٱلْآخِر", transliteration: "Al-Akhir", meaningEnglish: "The Last", explanation: "The One who will remain after all things end." },
  { number: 75, arabic: "ٱلظَّاهِر", transliteration: "Adh-Dhahir", meaningEnglish: "The Manifest", explanation: "The One whose existence is evident through creation." },
  { number: 76, arabic: "ٱلْبَاطِن", transliteration: "Al-Batin", meaningEnglish: "The Hidden", explanation: "The One who is hidden from all senses." },
  { number: 77, arabic: "ٱلْوَالِي", transliteration: "Al-Wali", meaningEnglish: "The Governor", explanation: "The One who governs all affairs." },
  { number: 78, arabic: "ٱلْمُتَعَالِ", transliteration: "Al-Muta'ali", meaningEnglish: "The Most Exalted", explanation: "The One who is supremely exalted above all." },
  { number: 79, arabic: "ٱلْبَرّ", transliteration: "Al-Barr", meaningEnglish: "The Source of Goodness", explanation: "The One who is most kind and good to His servants." },
  { number: 80, arabic: "ٱلتَّوَّاب", transliteration: "At-Tawwab", meaningEnglish: "The Accepter of Repentance", explanation: "The One who accepts repentance again and again." },
  { number: 81, arabic: "ٱلْمُنْتَقِم", transliteration: "Al-Muntaqim", meaningEnglish: "The Avenger", explanation: "The One who retaliates against the wrongdoers." },
  { number: 82, arabic: "ٱلْعَفُوّ", transliteration: "Al-'Afuw", meaningEnglish: "The Pardoner", explanation: "The One who pardons and erases sins completely." },
  { number: 83, arabic: "ٱلرَّءُوف", transliteration: "Ar-Ra'uf", meaningEnglish: "The Compassionate", explanation: "The One of extreme kindness and gentleness." },
  { number: 84, arabic: "مَالِكُ ٱلْمُلْك", transliteration: "Malikul-Mulk", meaningEnglish: "Owner of Sovereignty", explanation: "The One who is the absolute King of all dominion." },
  { number: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَام", transliteration: "Dhul-Jalali Wal-Ikram", meaningEnglish: "Lord of Majesty and Generosity", explanation: "The One who possesses both majesty and generosity." },
  { number: 86, arabic: "ٱلْمُقْسِط", transliteration: "Al-Muqsit", meaningEnglish: "The Equitable One", explanation: "The One who is equitable and acts with justice." },
  { number: 87, arabic: "ٱلْجَامِع", transliteration: "Al-Jami'", meaningEnglish: "The Gatherer", explanation: "The One who gathers all on the Day of Judgement." },
  { number: 88, arabic: "ٱلْغَنِيّ", transliteration: "Al-Ghani", meaningEnglish: "The Self-Sufficient", explanation: "The One who is free of all needs." },
  { number: 89, arabic: "ٱلْمُغْنِي", transliteration: "Al-Mughni", meaningEnglish: "The Enricher", explanation: "The One who enriches whoever He wills." },
  { number: 90, arabic: "ٱلْمَانِع", transliteration: "Al-Mani'", meaningEnglish: "The Preventer", explanation: "The One who prevents harm from His servants." },
  { number: 91, arabic: "ٱلضَّارّ", transliteration: "Ad-Darr", meaningEnglish: "The Distresser", explanation: "The One who can allow harm to afflict whom He wills." },
  { number: 92, arabic: "ٱلنَّافِع", transliteration: "An-Nafi'", meaningEnglish: "The Propitious", explanation: "The One who brings benefit to whom He wills." },
  { number: 93, arabic: "ٱلنُّور", transliteration: "An-Nur", meaningEnglish: "The Light", explanation: "The One who is the light of the heavens and the earth." },
  { number: 94, arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", meaningEnglish: "The Guide", explanation: "The One who guides to the straight path." },
  { number: 95, arabic: "ٱلْبَدِيع", transliteration: "Al-Badi'", meaningEnglish: "The Originator", explanation: "The One who creates in a unique and wonderful way." },
  { number: 96, arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", meaningEnglish: "The Everlasting", explanation: "The One who will never cease to exist." },
  { number: 97, arabic: "ٱلْوَارِث", transliteration: "Al-Warith", meaningEnglish: "The Inheritor", explanation: "The One who inherits all things after they perish." },
  { number: 98, arabic: "ٱلرَّشِيد", transliteration: "Ar-Rashid", meaningEnglish: "The Guide to the Right Path", explanation: "The One who is perfectly wise in all affairs." },
  { number: 99, arabic: "ٱلصَّبُور", transliteration: "As-Sabur", meaningEnglish: "The Patient One", explanation: "The One who is patient and does not hasten punishment." },
];

export async function seedNamesOfAllah() {
  const names = NAMES.map((n) => ({ ...n, id: nanoid() }));
  await setNamesOfAllah(names);
  console.log(`Seeded ${names.length} Names of Allah`);
}
