import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import prayerRouter from "./prayer.js";
import streakRouter from "./streak.js";
import progressRouter from "./progress.js";
import sessionsRouter from "./sessions.js";
import duasRouter from "./duas.js";
import namesRouter from "./names.js";
import dailyRouter from "./daily.js";
import aiRouter from "./ai.js";
import namesOfAllahRouter from "./namesOfAllah.js";
import masjidRouter from "./masjid.js";
import zakatRouter from "./zakat.js";
import roomsRouter from "./rooms.js";
import giftsRouter from "./gifts.js";
import journalRouter from "./journal.js";
import halaqahRouter from "./halaqah.js";
import growthRouter from "./growth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(prayerRouter);
router.use(streakRouter);
router.use(progressRouter);
router.use(sessionsRouter);
router.use(duasRouter);
router.use(namesRouter);
router.use(dailyRouter);
router.use(aiRouter);
router.use(namesOfAllahRouter);
router.use(masjidRouter);
router.use(zakatRouter);
router.use(roomsRouter);
router.use(giftsRouter);
router.use(journalRouter);
router.use(halaqahRouter);
router.use(growthRouter);

export default router;
