// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/ImmersiveDark.tsx": () => import("../components/mockups/home-variants/ImmersiveDark.tsx"),
  "./components/mockups/home-variants/MagazineGrid.tsx": () => import("../components/mockups/home-variants/MagazineGrid.tsx"),
  "./components/mockups/home-variants/MinimalSacred.tsx": () => import("../components/mockups/home-variants/MinimalSacred.tsx")
};
